# Generated by Django 5.2.14 on 2026-05-27 14:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('phone', models.CharField(max_length=20)),
                ('workshop', models.CharField(choices=[('sustainable_poultry', 'Sustainable Poultry Farming Workshop (Saturdays, $45)'), ('farm_tour', 'Featherra Farm Guided Tour (Golden Hour, $20)'), ('flock_consulting', 'Starter Flock Consulting Session (1-on-1, $75)')], max_length=100)),
                ('date', models.DateField()),
                ('tickets', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('message', models.TextField(blank=True, help_text='Optional custom requests or dietary needs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Blank if only subscribing to newsletter', max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()])),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('is_newsletter', models.BooleanField(default=False, help_text='True if this is a newsletter signup')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('eggs', 'Eggs'), ('meat', 'Poultry Meat'), ('chicks', 'Starter Chicks'), ('experiences', 'Farm Experiences')], max_length=30)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('unit', models.CharField(help_text='e.g. dozen, kg, starter pack, ticket', max_length=30)),
                ('image_name', models.CharField(help_text='Asset image name in the React frontend', max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('is_organic', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(help_text='Short introductory text for the service card')),
                ('details', models.TextField(help_text='Extended detailed information shown in modals')),
                ('image_name', models.CharField(help_text='Asset image file name or key in the React frontend', max_length=100)),
                ('cta_text', models.CharField(default='Learn More', max_length=50)),
                ('icon', models.CharField(help_text='Lucide-react icon name representing this service', max_length=50)),
                ('order', models.IntegerField(default=0, help_text='Ordering rank for display')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
